name: Hello CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from Мухтар Жумабек!"

      - name: Show OS info
        run: uname -a
